spring:
  application:
    name: url-trimify-backend

  datasource:
    url: jdbc:mysql://localhost:3306/trimify_db
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
