services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trimify_db
    ports:
      - "3306:3306"
    volumes:
      - ./url-trimify-data:/var/lib/mysql
    networks:
      - trimify

networks:
  trimify:
    name: timify
